version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/textengine/public_html/
  - source: /index.js
    destination: /var/www/textengine/public_html/
  - source: /package.json
    destination: /var/www/textengine/public_html/
  - source: /game-disks
    destination: /var/www/textengine/public_html/game-disks
  - source: /styles
    destination: /var/www/textengine/public_html/styles
  - source: /fonts
    destination: /var/www/textengine/public_html/fonts
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
