version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /index.js
    destination: /var/www/html/
  - source: /package.json
    destination: /var/www/html/
  - source: /game-disks
    destination: /var/www/html/game_disks
  - source: /styles
    destination: /var/www/html/fonts
  - source: /game-disks
    destination: /var/www/html/styles
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
