Description:
  This is a basic service and task definition template for ECS

Parameters:

  YourName:
    Description: What is your first name? Please enter a single word with only letters.
    Type: String

  ServiceName:
    Description: The name of the service
    Default: yourName-service
    Type: String

  ServiceRole:
    Description: Service role
    Default: ecs-service-cap1-ECS-sandbox-ProductService-JMGAJOZC2NJ6
    Type: String
    
  VPC:
    Description: The VPC that the ECS cluster is deployed to
    Type: String
    Default: vpc-008f4c40c26a26cf8

  Cluster:
    Description: Please provide the ECS Cluster ID that this service should run on
    Type: String
    Default: cap1-ECS-sandbox

  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 2

  Listener:
    Description: The Application Load Balancer listener to register with
    Type: String
    Default: arn:aws:elasticloadbalancing:us-east-2:474730797349:listener/app/cap1-ECS-sandbox/4085a4d47a77dac3/f5204b731bf9e4f2

  ContainerName:
    Type: String
    Default: yourName

Resources:
  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref ServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: 8001
          TargetGroupArn: !Ref TargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Essential: true
          Image: 275396840892.dkr.ecr.us-east-1.amazonaws.com/ecs-refarch-cloudformation/product-service:1.0.0
          Memory: 128
          PortMappings:
            - ContainerPort: 8001
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::YourName
      RetentionInDays: 7

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /{$YourName}
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: arn:aws:elasticloadbalancing:us-east-2:474730797349:loadbalancer/app/cap1-ECS-sandbox/4085a4d47a77dac3
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref YourName
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  # This IAM Role grants the service access to register/unregister with the
  # Application Load Balancer (ALB). It is based on the default documented here:
  # http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_IAM_role.html